### ISSUE TITLE
Cannot connect to WAX610 after FW update

### ISSUE THREAD

**Issue by pwm802** [rroller/netgear#19]
## Version of the custom_component
I couldn't find a version number in const.py

## Describe the bug
Updated WAX610 firmware to V10.5.0.16 then the HA netgear integration could not connect to WAX610.  I tried to delete one AP and  add it again without success.

## Debug log

2023-08-22 10:21:22.953 DEBUG (MainThread) [custom_components.netgear_wax] Creating client with username admin
2023-08-22 10:21:22.953 DEBUG (MainThread) [custom_components.netgear_wax] Checking for firmware updates
2023-08-22 10:21:23.221 DEBUG (MainThread) [custom_components.netgear_wax] Creating client with username admin
2023-08-22 10:21:23.221 DEBUG (MainThread) [custom_components.netgear_wax] Checking for firmware updates
2023-08-22 10:21:23.638 ERROR (Thread-109 (init_websocket)) [websocket] [Errno 113] Host is unreachable - goodbye
2023-08-22 10:21:24.513 DEBUG (MainThread) [custom_components.netgear_wax] Logging in with username admin
2023-08-22 10:21:24.756 DEBUG (MainThread) [custom_components.netgear_wax] Logging in with username admin
2023-08-22 10:21:25.604 DEBUG (MainThread) [custom_components.netgear_wax] login security token response={ "status": 401 }
2023-08-22 10:21:25.604 DEBUG (MainThread) [custom_components.netgear_wax] Failed to read current state
Traceback (most recent call last):
File "/config/custom_components/netgear_wax/__init__.py", line 118, in _async_update_data
self._state = await self.client.async_get_state(check_firmware)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/netgear_wax/client_wax.py", line 93, in async_get_state
result = await self.async_post(request_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/netgear_wax/client_wax.py", line 199, in async_post
await self.async_login()
File "/config/custom_components/netgear_wax/client_wax.py", line 57, in async_login
raise Exception("Could not get security token: " + text)
Exception: Could not get security token: { "status": 401 }
2023-08-22 10:21:25.634 DEBUG (MainThread) [custom_components.netgear_wax] Finished fetching netgear_wax data in 2.681 seconds (success: False)
2023-08-22 10:21:25.899 DEBUG (MainThread) [custom_components.netgear_wax] login security token response={ "status": 401 }
2023-08-22 10:21:25.899 DEBUG (MainThread) [custom_components.netgear_wax] Failed to read current state
Traceback (most recent call last):
File "/config/custom_components/netgear_wax/__init__.py", line 118, in _async_update_data
self._state = await self.client.async_get_state(check_firmware)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/netgear_wax/client_wax.py", line 93, in async_get_state
result = await self.async_post(request_data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/netgear_wax/client_wax.py", line 199, in async_post
await self.async_login()
File "/config/custom_components/netgear_wax/client_wax.py", line 57, in async_login
raise Exception("Could not get security token: " + text)
Exception: Could not get security token: { "status": 401 }
2023-08-22 10:21:25.900 DEBUG (MainThread) [custom_components.netgear_wax] Finished fetching netgear_wax data in 2.679 seconds (success: False)

**Comment by rroller** [comment]
Thanks. I will close this and use https://github.com/rroller/netgear/issues/18 to track this issue. I see what's wrong now

**Comment by rroller** [comment]
This should be fixed in the latest version of the plugin, please try that.
