### ISSUE TITLE
[WAX615] Cannot add the integration: Username, Password, or Address is wrong.

### ISSUE THREAD

**Issue by sesardelaisla** [rroller/netgear#20]
## Version of the custom_component
0.1.4

## Device information

Netgear WAX615
Firmware version: V10.5.0.14

## Configuration

```
logger:
  default: info
  logs:
    custom_components.netgear_wax: debug
```

Nothing else related to this component is included in `configuration.yaml`.

## Describe the bug
Upon trying to add the integration, the following error is displayed:

`Username, Password, or Address is wrong.`

I have triple checked that fields are correct.

## Debug log

Pasting the relevant log lines found in `home-assistant.log` after enabling debug logs for `custom_components.netgear_wax`:

```
2023-08-24 16:43:54.135 DEBUG (MainThread) [custom_components.netgear_wax] Creating client with username admin
2023-08-24 16:43:55.092 DEBUG (MainThread) [custom_components.netgear_wax] Logging in with username admin
2023-08-24 16:43:56.590 DEBUG (MainThread) [custom_components.netgear_wax] login security token response={ "status": 401 }
2023-08-24 16:43:56.591 ERROR (MainThread) [custom_components.netgear_wax] Failed: Could not get security token: { "status": 401 }
Traceback (most recent call last):
  File "/config/custom_components/netgear_wax/config_flow.py", line 87, in _test_credentials
    state = await client.async_get_state()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_wax/client_wax.py", line 93, in async_get_state
    result = await self.async_post(request_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/netgear_wax/client_wax.py", line 199, in async_post
    await self.async_login()
  File "/config/custom_components/netgear_wax/client_wax.py", line 57, in async_login
    raise Exception("Could not get security token: " + text)
Exception: Could not get security token: { "status": 401 }
```

Looking forward to getting some feedback. Thanks!

**Comment by rroller** [comment]
Thanks. I will close this and use https://github.com/rroller/netgear/issues/18 to track this issue. I see what's wrong now

**Comment by rroller** [comment]
This should be fixed in the latest version of the plugin, please try that.

**Comment by sesardelaisla** [comment]
Now it’s working. Thanks!
