### ISSUE TITLE
NetgearDataUpdateCoordinator' is not defined

### ISSUE THREAD

**Issue by elad-bar** [rroller/netgear#4]
## Describe the bug
On startup there are 4 errors with stack trace as below, 1 per device,
It seems that all components are working correctly.

## Debug log
```
today at 4:36:30 PM 2021-08-22 16:36:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ************ for binary_sensor
today at 4:36:30 PM Traceback (most recent call last):
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
today at 4:36:30 PM     result = await component.async_setup_entry(hass, self)  # type: ignore
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 144, in async_setup_entry
today at 4:36:30 PM     return await component.async_setup_entry(entry)
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 149, in async_setup_entry
today at 4:36:30 PM     platform = await async_prepare_setup_platform(
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/setup.py", line 329, in async_prepare_setup_platform
today at 4:36:30 PM     platform = integration.get_platform(domain)
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
today at 4:36:30 PM     cache[full_name] = self._import_platform(platform_name)
today at 4:36:30 PM   File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
today at 4:36:30 PM     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
today at 4:36:30 PM   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
today at 4:36:30 PM     return _bootstrap._gcd_import(name[level:], package, level)
today at 4:36:30 PM   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
today at 4:36:30 PM   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
today at 4:36:30 PM   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
today at 4:36:30 PM   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
today at 4:36:30 PM   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
today at 4:36:30 PM   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
today at 4:36:30 PM   File "/config/custom_components/netgear_wax/binary_sensor.py", line 26, in <module>
today at 4:36:30 PM     class NetgearBinarySensor(NetgearBaseEntity, BinarySensorEntity):
today at 4:36:30 PM   File "/config/custom_components/netgear_wax/binary_sensor.py", line 29, in NetgearBinarySensor
today at 4:36:30 PM     def __init__(self, coordinator: NetgearDataUpdateCoordinator, config_entry, sensor_type: str):
today at 4:36:30 PM NameError: name 'NetgearDataUpdateCoordinator' is not defined
```

**Comment by rroller** [comment]
Interesting. I don't yet see how this is happening
