### ISSUE TITLE
async_stop() missing 1 required positional argument: 'event'

### ISSUE THREAD

**Issue by elad-bar** [rroller/netgear#5]
Upon reloading the component throws a missing argument exception

## Debug log
```
today at 10:28:29 AM 2021-08-23 10:28:29 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry **-******-** for netgear_wax
today at 10:28:29 AM Traceback (most recent call last):
today at 10:28:29 AM   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 432, in async_unload
today at 10:28:29 AM     result = await component.async_unload_entry(hass, self)  # type: ignore
today at 10:28:29 AM   File "/config/custom_components/netgear_wax/__init__.py", line 166, in async_unload_entry
today at 10:28:29 AM     await coordinator.async_stop()
today at 10:28:29 AM TypeError: async_stop() missing 1 required positional argument: 'event'

```

**Comment by rroller** [comment]
Than you!

released in https://github.com/rroller/netgear/releases/tag/0.1.2
